### ISSUE TITLE
check out issue in clicshopping.... stuck on shipping address page.

### ISSUE THREAD

**Issue by AirnFire** [ClicShopping/ClicShopping_V3#12]
i have installed the clicshopping software now i'm exploring it.... it's not allowing me to checkout.... just stuck on shipping address.

**Comment by ClicShopping** [comment]
Do you install the Shipping Apps  (configuration) ?

**Comment by AirnFire** [comment]
I installed it through softaculous on server..so kindly elaborate what exactly is shipping app(configuration)??

**Comment by ClicShopping** [comment]
Go to your admin / Configuration / Shipping modules

**Comment by AirnFire** [comment]
Yes it's status is checked means installed

**Comment by ClicShopping** [comment]
Is it b2b registration or b2c. If b2b you must to activate in customer / member

**Comment by AirnFire** [comment]
It shows a black screen when I go to member b2b.... And when a new member make an account it doesn't allow me to activate the account. It shows error

**Comment by ClicShopping** [comment]
Could you send me the link to your administration if it's possible?

**Comment by ClicShopping** [comment]
look there is you have the problem : https://www.clicshopping.org/demo/ClicShoppingAdmin835/

**Comment by AirnFire** [comment]
Let me see.... thank you so much for helping. I'll get back to you again if my error won't resolve.

**Comment by AirnFire** [comment]
hi there..... i'm using english language in my version but on admin side under tools manu it's showing me some french words can you kindly tell me how can i edit them??

**Comment by ClicShopping** [comment]
2 solution you can change the file or inside the admin you can change also the terms. But be carefull il you reset all the terms you remove everything

**Comment by AirnFire** [comment]
What do you mean by reseting the terms kindly elaborate

**Comment by ClicShopping** [comment]
tested works fine
