### ISSUE TITLE
error in uploading new products..... don't show image of my product on shop 

### ISSUE THREAD

**Issue by AirnFire** [ClicShopping/ClicShopping_V3#13]
i'm trying to add a new product but it's not showing any picture with it kindly tell me what to do.

**Comment by ClicShopping** [comment]
Hello,
Check this point
- Image Directory 755 or 777

**Comment by AirnFire** [comment]
777

**Comment by ClicShopping** [comment]
When you insert an image as a product via ckedior et elfinder do you see the image inside the box ?
If you go inside the description product and click on the image,  do you find your image?
Can you try by this way to upload an image, include inside the description and look if you see your image on the catalog (product description)

**Comment by AirnFire** [comment]
This is how I upload it.
![Uploading 20210429_183527.jpg…]()

**Comment by AirnFire** [comment]
And when I say update I see this screen
![Uploading 20210429_183649.jpg…]()

**Comment by ClicShopping** [comment]
I can not see the image above

**Comment by AirnFire** [comment]
Error says mydirectory.org can't currently handle the request

**Comment by ClicShopping** [comment]
Do you see at the top, right an error (yellow icon) ?
Also, maybe the problem come from hoster. check with him.

**Comment by AirnFire** [comment]
There's no yellow icon and I did checked it with host that's not the case..... it's just not saving my request but in images directory when I manually check there is image available

**Comment by ClicShopping** [comment]
ok could you look inside you db, products_images and products table and give me what you see inside

**Comment by AirnFire** [comment]
In products table I have model, wan, price, date, admin user and type.... all other columns are blank

**Comment by ClicShopping** [comment]
It's weird because, if there is an error inside the code, you must see a yellow icon appear at your right (horizontal menu).

**Comment by AirnFire** [comment]
In db its storing other data but not img...

**Comment by ClicShopping** [comment]
What is the size of your image, because you can have an impact. If it's too big, it does not take. try in 1024 or 800 it's enought

**Comment by AirnFire** [comment]
I'm uploading an image from the demo data I have from clicshopping pkg

**Comment by ClicShopping** [comment]
witch image, jpg,png,webp.

**Comment by AirnFire** [comment]
Jpg

**Comment by ClicShopping** [comment]
I can not help you more if I have no access. Could you give your admin link after you can remove your post

**Comment by AirnFire** [comment]
Actually I'm not authorize to share admin info..... can you please tell me what could possibly be wrong

**Comment by ClicShopping** [comment]
I have no idea for a moment until I test. Try to install in your desktop. There is some application on the web to create a little server (easyphp for example with php 8.0)

**Comment by AirnFire** [comment]
Thank you so much let me create a server and I'll be in touch.

**Comment by AirnFire** [comment]
http://deals.delta3t.com/ClicShoppingAdmin/
username: info@sci-sageza.org
password: DEALS_B2B_sageza#123

these  are the credentials of my clicshopping site 
1. kindly check on the website why it doesn't check out after I have selected a product to order
2. and in the product section of the Admin dashboard the pictures don't upload.
3.  in B2B it doesn't allow me to activate a company account. It shows Error: Site Can't be Reached...cant't currently handle this request

![pic error](https://user-images.githubusercontent.com/59435182/116591335-204b4a80-a938-11eb-9c92-e0e53a47524f.JPG)

**Comment by AirnFire** [comment]
hi...... you there?? 
Kindly let me know when you're available, i'll share my credentials..... your help is really appreciated.

**Comment by AirnFire** [comment]
i have made the changes you have mentioned above  except https........... i couldn't find popen in my phpmanagerini.
kindly clear that do you want me to uninstall the app from server and install it again???

problem is still same it's not showing image.

**Comment by ClicShopping** [comment]
Do you have deleted the log ? If you want to resolve the situation, this is only way. Also mentionned you have restriction inside your php.ini and it's important to find all has an impact on the software

**Comment by AirnFire** [comment]
i have removed restrictions and yes i have deleted the logs.

**Comment by ClicShopping** [comment]
tested works fine, depend on your server configuration
