### ISSUE TITLE
 ClicShopping  version 3.313 throws There was a problem connecting to the database server. Please verify the connection parameters and try again. error

### ISSUE THREAD

**Issue by aruns807** [ClicShopping/ClicShopping_V3#15]
I was in the process of manual installation of ClicShopping  3.313 on  PHP 8.0, MYSQL 7.0, Apache 2.4

(https://github.com/ClicShopping/ClicShopping_V3) version 3.313](https://github.com/ClicShopping/ClicShopping_V3/releases/tag/version3.313) 

![click-github](https://user-images.githubusercontent.com/7455555/154060320-92a5b761-478b-4523-b478-b9763b238f72.png)

**Comment by ClicShopping** [comment]
Hello,
take the latest release

**Comment by ClicShopping** [comment]
Witch Db do you use, demo or norma, french or English ?

**Comment by ClicShopping** [comment]
tested on php 8.1 works fine french, english and demo

**Comment by ClicShopping** [comment]
tested also on php 8.0.15, works fine. Under ubuntu.
Please let me know if you have always this problem or not and give me more information (do use Cpanel ?)

**Comment by aruns807** [comment]
> tested also on php 8.0.15, works fine. Under ubuntu. Please let me know if you have always this problem or not and give me more information (do use Cpanel ?)
Yes, tested also PHP 8.1 (Cpanel)

**Comment by ClicShopping** [comment]
@[aruns807](https://github.com/aruns807) and do you have always a problem ?

**Comment by aruns807** [comment]
Yes

**Comment by ClicShopping** [comment]
Ok I have a Cpanel hosting, I will test and come to you.Let me little time, I have a rdv soon

**Comment by aruns807** [comment]
OK, Thanks

**Comment by ClicShopping** [comment]
Tested with Cpanel on my side, no pb in php 8.0 and 8.1 
tested demo and normal (basic) no problem in english
But in French translation install, I have a constant problem, I will push a release more later with this modification
Without this, no problem also.

Let me know

**Comment by ClicShopping** [comment]
push a new version,let me know if you have the same problem. If not could you close the ticket? Tk

**Comment by aruns807** [comment]
Thanks Now working.(requirements upgraded)
