### ISSUE TITLE
Version 3.3.29 shows blank page on trying to add new Category and Brands

### ISSUE THREAD

**Issue by prbt2016** [ClicShopping/ClicShopping_V3#19]
**Describe the bug**
I was in the process of installing Clicshopping version 3.3.29 on Centos 7 with Apache 2.4, MYSQL 5.7, PHP 8.1. 

However on successful installation on visiting, 

Catalog->Categories->New Categorie and after entering category name and clicking on 'Update' redirects to 

http://{{DOMAIN.COM}}/clicshop/ClicShoppingAdmin/index.php?A&Catalog%5CCategories&Categories&Insert&cPath=0&cID=

and I checked the same URL in browser console and it throws 500 internal server error 

But when I checked under Categories the list of categories those categories are shown. Seems to be a redirect issue.

This also occurs under Catalog->Brands->New brand  and enter the brand name and clicking on Insert redirects to 

http://{{DOMAIN.COM}}/clicshop/ClicShoppingAdmin/index.php?A&Catalog%5CManufacturers&Manufacturers&Insert

And after checking the same for Brand list no brands are added however.

**To Reproduce**
1. Go to 'Catalog->Categories->New Categorie' / 'Catalog->Brands->New brand'
2. Click on 'Update after  Catalog->Categories->New Categorie' / Click on 'Insert' after visiting Catalog->Brands->New brand
3. Blank page is shown
4. After turning error reporting on under php.ini too, no error is shown.

**Expected behavior**
Expected  that category list and brand list to be shown properly.

**Desktop (please complete the following information):**
 - OS : Centos 7 
 - Browser :  Mozilla Firefox
 - Version : 104.0

**Additional context**
I have an old installation of 3.3.28 on the same server and the above things i.e categories and brands work absolutely fine.

Could you please debug the issue and replicate this on your server?.

**Comment by ClicShopping** [comment]
Yes exact, 

HTMLOverrideAdmin::getWysiwygImageAlone() does not exist must be used like this
$CLICSHOPPING_Wysiwyg::getWysiwygImageAlone()

I will updapte this point today or tomorrow on Github.

Thank you for this report.

**Comment by prbt2016** [comment]
Hello @ClicShopping ,

I checked with 3.3.30 and the above issue is resolved. Thanks a lot for the fix.

Regards.
