### ISSUE TITLE
Integrity constraint violation: 1048 Column 'parent_id' cannot be null 

### ISSUE THREAD

**Issue by GaneshKandu** [ClicShopping/ClicShopping_V3#24]
**Describe the bug**"
I am getting this error while install of version3.403
![image](https://user-images.githubusercontent.com/12833130/203012172-91bd64d5-47fc-4f35-b2c6-c70f0b2fc226.png)

**To Reproduce**
1. Go to '/install'
2. Click on 'start installation procedure'
3. fill all the fields ( Install Demo Database as normal )
4. Click on 'continue'
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/12833130/203012172-91bd64d5-47fc-4f35-b2c6-c70f0b2fc226.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox 104.0.2

**Comment by GaneshKandu** [comment]
![Screenshot 2022-11-21 at 14-54-07 ClicShopping Social E-Commerce B2B_B2C Open Source Solutions](https://user-images.githubusercontent.com/12833130/203013974-ce84b53f-c0e8-40d4-90f9-2b9e688c2904.png)

**Comment by ClicShopping** [comment]
done for the next release
