### ISSUE TITLE
Regarding Clicshopping 3.407 version

### ISSUE THREAD

**Issue by prbt2016** [ClicShopping/ClicShopping_V3#27]
Hello @ClicShopping ,

Under the official site announcements https://www.clicshopping.org/forum/ , I can see that Clicshopping 3.407 version has released. 

![image](https://user-images.githubusercontent.com/17871448/208356809-286f6e2b-90b6-4a24-8088-19246f908f27.png)

However on clicking the link i.e 

https://github.com/ClicShopping/ClicShopping_V3/releases

The latest version shown under releases is 3.406 and not 3.407. 

Please let me know when it shall be available for download?.

Regards.

**Comment by ClicShopping** [comment]
Hello,

Just communication error on the forum.
Thank you to contact. Rectify

------------------------
Cordialement,
*loïc Richard*


Le lun. 19 déc. 2022 à 00:51, Prashant Tondale ***@***.***> a
écrit :
