### ISSUE TITLE
Issue in install of  ClicShopping_V3 3.408

### ISSUE THREAD

**Issue by GaneshKandu** [ClicShopping/ClicShopping_V3#28]
**Describe the bug**

Getting this error on continue button of ``/install/install.php``

``SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'administrator_menu VALUES(792, 'index.php?A&Tools\\Upgrade&Upgrade', 644, 5, 1, ' at line 1``

**To Reproduce**
1. Extract package on webroot
2. Give all writable permissions and ownership
3. fill dalabase details with prefix and normal demo install
4. click on continue 
5. See error

**Screenshots**

![img_20230210](https://user-images.githubusercontent.com/12833130/218053765-999ffbba-7e69-4424-a7d2-388b0f8e29e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 108.0.1

**Additional context**
Server OS : Centos 7.9
php : 8.1.2
mysql : 5.7.37

**Comment by ClicShopping** [comment]
Confirmed, solution on the way

**Comment by ClicShopping** [comment]
resolved, push a new release
