### ISSUE TITLE
elFinder doesn't work as expecting

### ISSUE THREAD

**Issue by superthin** [ClicShopping/ClicShopping_V3#3]
When editing a category (eg. Desktops in demo Admin of ClicShopping), if we want to upload an image to replace current image, we cannot because:

![Selection_044](https://user-images.githubusercontent.com/3869829/67499957-1c3bce00-f6ac-11e9-998c-080e61bde470.jpg)

will create the result:

![ERROR 403 - Forbidden! - Google Chrome_045](https://user-images.githubusercontent.com/3869829/67500107-6a50d180-f6ac-11e9-8be6-64e5cc77db53.jpg)

**Comment by oitsuki** [comment]
remove the htacess; It must work

**Comment by ClicShopping** [comment]
fixed
