### ISSUE TITLE
Nothing happens when submiting register form (pro account)

### ISSUE THREAD

**Issue by superthin** [ClicShopping/ClicShopping_V3#4]
When we choose [Open a professionnal Account](https://demo.clicshopping.org/demo/index.php/Account/CreatePro), fill form and submit: nothing happened: no note, no email.

**Comment by oitsuki** [comment]
Works, 
I receive an email as expected and the message
The email must be set with SMTP, no Sendmail because some hoster makes restriction.

**Comment by ClicShopping** [comment]
Works,
I receive an email as expected and the message
The email must be set with SMTP, no Sendmail because some hoster makes restriction.
