### ISSUE TITLE
Category image not save and display nowhere

### ISSUE THREAD

**Issue by superthin** [ClicShopping/ClicShopping_V3#5]
When we create or edit a category (containter of products), if we post ab image as URL, it works. But if we browse server and upload an image, image load to left pane but not load to preview image zone. When we click button **Update** , path to image doesn't save to DB.

Where is a thumbnail image of a category displaying on store? I cannot find.

**Comment by ClicShopping** [comment]
For categories, insert, update (tab image) works fine.
The preview on the right works, no pb with the db
There is no thumbail generated like the products for the moment and save in /sources/images directory.
