### ISSUE TITLE
Open an account page wihtout forms

### ISSUE THREAD

**Issue by SplashZK** [ClicShopping/ClicShopping_V3#7]
Hi, i have already install a fresh version oh ClicShopping whitout demo database, but when i click to create acount at the top of the index the page load but without forms to select the type of acount, is there a configuration that a i need to do?

in the image the red rectangle is my server and the green one is the demo version

![shopq](https://user-images.githubusercontent.com/28606261/88962069-86048c00-d26b-11ea-8f92-aa4f35bf53d2.png)

**Comment by ClicShopping** [comment]
Go to Design - Customer account - and look if the different modules are installed.
If yes try to uninstall and reinstall.

**Comment by SplashZK** [comment]
its a bug with the url
the url generated is localhost/ClicShopping/shop/index.php?Account&Login
but if i change for localhost/ClicShopping/shop/index.php?Account&LogIn
the page works correctly, note that i just change one letter in **Login** 
where is the right place to change this in code or i can change this in admin panel?

**Comment by SplashZK** [comment]
i changed the line 73 **Login** to **LogIn** in /source/template/Default/modules/modules_header/template_html/multi_template_default.php and it works
i don´t know if this is an global error or just mine, but for me this was the fix

**Comment by ClicShopping** [comment]
Well done, there is a bug on that, my server do not me a report on that.
Thank you
